### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by ScottBClary** [RFC-HyugaClan/FEC#21]
https://github.com/RFC-HyugaClan/FEC/blob/e9c0adabacfefb787ecb4fa28d45d5593d6fab41/client/src/RatingsAndReviews/Ratings/Characteristics.jsx#L9

May want to comment on why a falsey value for fit would warrant this.

**Comment by JasonDGates** [comment]
There are 6 characteristics that each product can have, however they may not have all 6 characteristics. This checks if the product has a specific characteristic (in this case "Fit") and if it is, it displays this ratings section. If not, it is not displayed.

**Comment by JasonDGates** [comment]
No change needed.
