### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by ScottBClary** [RFC-HyugaClan/FEC#26]
#### Description 

After opening an image thumbnail, it expands to fill up screen. To close, you must click on the picture. I think it is more intuitive to click _outside_ of the picture to close it.

#### Screenshots 
![Screen Shot 2022-06-04 at 10 51 19 AM](https://user-images.githubusercontent.com/14322119/172013939-4b0b1b0d-e9a6-4fb3-9227-a7590105455f.png)

#### Files 
FEC/client/src/RatingsAndReviews/Reviews/Thumbnails.jsx

**Comment by JasonDGates** [comment]
Refactored main modal so that clicking anywhere closes the modal.
