### ISSUE TITLE
UX Issue Review List

### ISSUE THREAD

**Issue by Casterwield** [RFC-HyugaClan/FEC#31]
#### Description
A clear and concise description of what the issue is about.
#### Screenshots (if ui based)
![Image 6-4-22 at 12 31 PM](https://user-images.githubusercontent.com/85713447/172018779-95fd1f64-2682-43b9-b7c6-b7a6d500c35e.jpg)
#### Files
[Files](https://github.com/RFC-HyugaClan/FEC/blob/main/client/src/RatingsAndReviews/Reviews/ReviewsList.jsx)
#### To Reproduce
Click expand review list, attempt to click add new review
#### Tasks (optional)
- [x] Isolate which file is causing the issue
- [x] Troubleshoot and fix issue

**Comment by JasonDGates** [comment]
This is caused by different window sizing. The write a new review button is oustide the main container and is altering its position. I changed the container to encompass this button. Refactored and tested!
