### ISSUE TITLE
String from character code is not needed

### ISSUE THREAD

**Issue by Casterwield** [RFC-HyugaClan/FEC#33]
#### Description
This can be more easily represented and controlled via using regex and unicode, rather than string from character code, we can instead just use '\u{characterCode}' which will produce the character in question. 'u\{character code} u\ {character cod}' would produce two of that character.
#### Files
https://github.com/RFC-HyugaClan/FEC/blob/e9c0adabacfefb787ecb4fa28d45d5593d6fab41/client/src/RatingsAndReviews/Reviews/StarRating.jsx#L6-L7
#### Tasks (optional)
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at. - [ ] Consider if this use case would improve your code readability/access to variables
- [x] Change if it would improve

**Comment by JasonDGates** [comment]
Refactored into unicode
