### ISSUE TITLE
Can move code to meet display spec from BRD

### ISSUE THREAD

**Issue by Casterwield** [RFC-HyugaClan/FEC#34]
#### Description
Moving the label descriptor for the characteristic to above the "size:" string and setting it equal to the currently selected option will allow you to meet BRD specs relatively easily.
#### Files
https://github.com/RFC-HyugaClan/FEC/blob/e9c0adabacfefb787ecb4fa28d45d5593d6fab41/client/src/RatingsAndReviews/Reviews/WriteNewReview/Characteristics.jsx#L11-L20
#### Tasks (optional)
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at. - [ ] Task 1
- [x] Task 2

**Comment by JasonDGates** [comment]
Design updated
